#!/bin/bash

set -e # Stop at the first error

BASE="${PWD}"

echo ">>> Check 'install from local' workflow"
{
  APP_NAME="hello"

  "${BASE}/bin/brt" app install from local "${APP_NAME}" "${BASE}/samples/hello"
  "${BASE}/bin/brt" app lst
  "${BASE}/bin/brt" app run "${APP_NAME}"
  "${BASE}/bin/brt" app uninstall "${APP_NAME}"
}

echo ">>> Check 'install from git' workflow"
{
  APP_NAME="hello-remote"

  "${BASE}/bin/brt" app install from git "${APP_NAME}" "https://github.com/bashapp/hello.git"
  "${BASE}/bin/brt" app lst
  "${BASE}/bin/brt" app run "${APP_NAME}"
  "${BASE}/bin/brt" app uninstall "${APP_NAME}"
}
